### ISSUE TITLE
fix: maas and postgres to use `_helpers.tpl` rather than `helm-toolkit`

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm-addons#5]
as part of the migration of maas and postgresql (PR #4), and to allow these charts to function outside of openstack-helm (remove the built in functions of `helm-toolkit`), `_helpers.tpl` should be leveraged. on their own, these charts will not work. this will increase the usability of these charts beyond openstack-helm (our needs).

**REQUIREMENT:** This issue requires #4 be merged in first (before the work on this issue can be started).

**Comment by intlabs** [comment]
@v1k0d3n I could fix this this morning if you like? Should only take 10 mins or so.
